server:
  port: 80


spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://localhost:3307/mydb?allowPublicKeyRetrieval=true
    username: realkk
    password: qwer@

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
